### ISSUE TITLE
Allow the same state name in different parallel machines

### ISSUE THREAD

**Issue by karl** [sverweij/state-machine-cat#17] opened 2018-07-03 20:29 UTC
When creating parallel machines, every state must have a unique name.

For example:

```
parallel {
    bold{
        first.on -> first.off;
        first.off -> first.on;
    },
    underline{
        second.on -> second.off;
        second.off -> second.on;
    };
};
```

![image](https://user-images.githubusercontent.com/3681/42242760-f198e638-7f06-11e8-962e-b4f8b387a872.png)

I'd like to be able to have the states just be named `on` and `off`.

### Expected Behavior/Possible Solution

I wonder if when using the `json` representation of the state machine we could have the idea of states having something like a `displayName` that when provided is used for rendering the state name.

This would allow me to use the current `name` field as a unique id, with `displayName` giving a nice compact output.

### Context

I'm working on a library to convert `xstate` state chart descriptions in svg diagrams using `state-machine-cat`.

With `xstate` you can re-use the same state name across each part of a parallel or nested state machine. I'd like to be able to preserve these state names in the diagram output from `state-machine-cat`.

**Comment by sverweij** [comment] 2018-07-03 22:18
@karl Thanks for interest in state-machine-cat, and for raising this issue. It'll probably make state-machine-cat a little better...

I think your possible suggestion is the way to go; separating name and displayName (or `id` and `label`) is sound software engineering. It'll get the drag out of typing really long names lots of times as well. I designed that into [msgenny](https://mscgen.js.org/tutorial.html#naming-entities-explicit-order) from the start, but for state-machine-cat I didn't. Lazy, I guess :-) Also the msgenny approach (label behind dots) wouldn't work in state-machine-cate because the dots are already in use to separate the state's name from its activities.

> Aside: _scoping_ state names ("id's") - so they'd have to be unique within their own containing state only - is worth considering as well. I'll have a peek at what the scxml (and/ or xstate) folks did there.

Implementation wise I would propose to slap the displayName (`label`) in a square brackets construct, just before the `:`. That enables us to later expand it with other attributes (e.g. colors might make some folks happy):
```smcat
unset [label="alarm not set"],
set [label="alarm set"]: show a bell;

unset => set: time entered;
```

The json would then look something like this:
```json
{
    "states": [{
        "name": "unset",
        "label": "alarm not set",
        "type": "regular"
    }, {
        "name": "set",
        "label": "alarm set",
        "type": "regular",
        "activities": "show a bell"
    }],
    "transitions": [{
        "from": "unset",
        "to": "set",
        "label": "enter time",
        "event": "enter time"
    }]
}
```

In scjson/ scxml we can put the label into the `name` attribute that the scxml designers made for this. And pray we _can_ put any string in there we want (unlike e.g. the id and event attributes ...)
```xml
...
<state id="unset" name="alarm not set">
    <transition event="enter_time" target="set"/>
</state>
...
```

![untitled](https://user-images.githubusercontent.com/4822597/42246298-6c6487f4-7f1c-11e8-8dbc-d565e8b5f776.png)

**Comment by karl** [comment] 2018-07-04 05:55
That all sounds great!

Let me know if there is anything I can do to help out with this.

**Comment by sverweij** [comment] 2018-07-04 10:29
@karl thanks for the offer! If you could give the new version a try and supply feedback (like you did with #15) that'd be massively helpful.

Version `2.7.0-beta-1` is now on npm (with the beta tag) that has
- the ability to give states display names (with a 'label' attribute)
- a dot (and hence svg) reporter that output display name instead of the name if it's there.
- (an smcat reporter that reproduces the input, formatted, including any labels)

> Also: I've checked the scxml spec 
> - they don't have separation between id and name as I initially understood - so the scxml/ scjson renderers stay untouched).
> - they don't scope id's to nested states - "In a conformant SCXML document, the values of all attributes of type "id" must be unique **within the session**. (...)" [w3 scxml spec, IDs section]( https://www.w3.org/TR/scxml/#IDs) - emphasis mine.

**Comment by karl** [comment] 2018-07-04 16:36
I'm very happy to test this and supply feedback. I should have time to look at it tomorrow.

Thanks for the quick turnaround on this!

**Comment by karl** [comment] 2018-07-04 16:41
Just had a chance to have a quick play around and this looks great!

![image](https://user-images.githubusercontent.com/3681/42288158-7c4ba72a-7fb1-11e8-8274-c0c22fae9006.png)

**Comment by sverweij** [comment] 2018-07-06 20:33
Thanks @karl both for requesting this feature and for trying the beta

The PR is merged and released a new major version of state-machine-cat. No worries; the version bump is major  because I had to make a small breaking change in the syntax to introduce the label attribute - see the (release notes)[https://github.com/sverweij/state-machine-cat/releases/tag/v3.0.0] for details).

**Closed** 2018-07-08 17:59 UTC
Labels: enhancement
